In [1]:
import pandas as pd
import numpy as np

from sklearn.preprocessing import StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.feature_selection import SelectKBest, f_regression
from sklearn.decomposition import PCA

In [2]:
df=pd.read_csv("auto-mpg.csv")

display(df.head())

    mpg  cylinders  displacement  ... model year  origin                   car name
0  18.0          8         307.0  ...         70       1  chevrolet chevelle malibu
1  15.0          8         350.0  ...         70       1          buick skylark 320
2  18.0          8         318.0  ...         70       1         plymouth satellite
3  16.0          8         304.0  ...         70       1              amc rebel sst
4  17.0          8         302.0  ...         70       1                ford torino

[5 rows x 9 columns]

In [3]:
numeric_columns=df.select_dtypes(include=np.number).columns

print("Numeric Colums:")
print(numeric_columns)

Numeric Colums:
Index(['mpg', 'cylinders', 'displacement', 'weight', 'acceleration',
       'model year', 'origin'],
      dtype='object')

In [4]:
categorical_colums=df.select_dtypes(include="object").columns

print("Categorical Colums:")
print(categorical_colums)

Categorical Colums:
Index(['horsepower', 'car name'], dtype='object')

In [5]:
df["origin"]=df["origin"].astype("object")

In [6]:
print(df.isnull().sum())

mpg             0
cylinders       0
displacement    0
horsepower      0
weight          0
acceleration    0
model year      0
origin          0
car name        0
dtype: int64

In [7]:
df=df.replace("?",np.nan)

In [8]:
print(df.isnull().sum())

mpg             0
cylinders       0
displacement    0
horsepower      6
weight          0
acceleration    0
model year      0
origin          0
car name        0
dtype: int64

In [9]:
df['horsepower']=pd.to_numeric(df["horsepower"])

In [10]:
df["horsepower"]=df["horsepower"].fillna(df["horsepower"].mean())

In [11]:
print(df.isnull().sum())

mpg             0
cylinders       0
displacement    0
horsepower      0
weight          0
acceleration    0
model year      0
origin          0
car name        0
dtype: int64

In [13]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler().set_output(transform="pandas")

numeric_cols = df.select_dtypes(include=["number"]).columns

scaled_data = scaler.fit_transform(df[numeric_cols])

scaled_data.head()

        mpg  cylinders  displacement  ...    weight  acceleration  model year
0  0.239362        1.0      0.617571  ...  0.536150      0.238095         0.0
1  0.159574        1.0      0.728682  ...  0.589736      0.208333         0.0
2  0.239362        1.0      0.645995  ...  0.516870      0.178571         0.0
3  0.186170        1.0      0.609819  ...  0.516019      0.238095         0.0
4  0.212766        1.0      0.604651  ...  0.520556      0.148810         0.0

[5 rows x 7 columns]

In [16]:
from sklearn.preprocessing import OneHotEncoder

# Dynamically select object columns to encode (e.g., 'origin', 'car name')
categorical_cols = df.select_dtypes(include=["object"]).columns

encoder = OneHotEncoder(
    handle_unknown="ignore",
    sparse_output=False
).set_output(transform="pandas")

encoded_data = encoder.fit_transform(df[categorical_cols])

display(encoded_data.head())

   origin_1  origin_2  ...  car name_vw rabbit c (diesel)  car name_vw rabbit custom
0       1.0       0.0  ...                            0.0                        0.0
1       1.0       0.0  ...                            0.0                        0.0
2       1.0       0.0  ...                            0.0                        0.0
3       1.0       0.0  ...                            0.0                        0.0
4       1.0       0.0  ...                            0.0                        0.0

[5 rows x 308 columns]

In [18]:
import numpy as np
import pandas as pd
from sklearn.feature_selection import SelectKBest, f_regression


y = df["mpg"]

numeric_features = scaled_data.drop(columns=["mpg"], errors="ignore")
X = pd.concat([numeric_features, encoded_data], axis=1)

X_numeric = X.select_dtypes(include=np.number)

selector = SelectKBest(
    score_func=f_regression,
    k=3
).set_output(transform="pandas")

X_selected = selector.fit_transform(X_numeric, y)

print(X_selected.head())

   cylinders  displacement    weight
0        1.0      0.617571  0.536150
1        1.0      0.728682  0.589736
2        1.0      0.645995  0.516870
3        1.0      0.609819  0.516019
4        1.0      0.604651  0.520556