In [1]:
import pandas as pd
import numpy as np

from sklearn.preprocessing import StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.feature_selection import SelectKBest, f_regression
from sklearn.decomposition import PCA

In [2]:
df=pd.read_csv("02 computer.csv")

display(df.head())

       age  income student credit_rating buys_computer
0     <=30    high      no          fair            no
1     <=30    high      no     excellent            no
2  31...40    high      no          fair           yes
3      >40  medium      no          fair           yes
4      >40     low     yes          fair           yes

In [3]:
df['age'] = df['age'].str.replace('31...40','31-40')
df

      age  income student credit_rating buys_computer
0    <=30    high      no          fair            no
1    <=30    high      no     excellent            no
2   31-40    high      no          fair           yes
3     >40  medium      no          fair           yes
4     >40     low     yes          fair           yes
5     >40     low     yes     excellent            no
6   31-40     low     yes     excellent           yes
7    <=30  medium      no          fair            no
8    <=30     low     yes          fair           yes
9     >40  medium     yes          fair           yes
10   <=30  medium     yes     excellent           yes
11  31-40  medium      no     excellent           yes
12  31-40    high     yes          fair           yes
13    >40  medium      no     excellent            no

In [4]:
x=df.iloc[:,0:4]
y=df['buys_computer']


x

      age  income student credit_rating
0    <=30    high      no          fair
1    <=30    high      no     excellent
2   31-40    high      no          fair
3     >40  medium      no          fair
4     >40     low     yes          fair
5     >40     low     yes     excellent
6   31-40     low     yes     excellent
7    <=30  medium      no          fair
8    <=30     low     yes          fair
9     >40  medium     yes          fair
10   <=30  medium     yes     excellent
11  31-40  medium      no     excellent
12  31-40    high     yes          fair
13    >40  medium      no     excellent

In [5]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test=train_test_split(
    x,
    y,
    test_size=0.2,
    random_state=1)

In [12]:
from sklearn.preprocessing import OrdinalEncoder
import pandas as pd

# Reset the datasets to raw split to avoid partial encoding state
x_train, x_test, y_train, y_test = train_test_split(
    x,
    y,
    test_size=0.2,
    random_state=1
)

# Define distinct encoders for each feature
oe_age = OrdinalEncoder(categories=[['<=30', '31-40', '>40']])
oe_income = OrdinalEncoder(categories=[['low', 'medium', 'high']])
oe_student = OrdinalEncoder(categories=[['no', 'yes']])
oe_credit = OrdinalEncoder(categories=[['fair', 'excellent']])

# Encode both train and test splits to keep them consistent
x_train_encoded = pd.DataFrame(index=x_train.index)
x_train_encoded['age'] = oe_age.fit_transform(x_train[['age']])
x_train_encoded['income'] = oe_income.fit_transform(x_train[['income']])
x_train_encoded['student'] = oe_student.fit_transform(x_train[['student']])
x_train_encoded['credit_rating'] = oe_credit.fit_transform(x_train[['credit_rating']])

x_test_encoded = pd.DataFrame(index=x_test.index)
x_test_encoded['age'] = oe_age.transform(x_test[['age']])
x_test_encoded['income'] = oe_income.transform(x_test[['income']])
x_test_encoded['student'] = oe_student.transform(x_test[['student']])
x_test_encoded['credit_rating'] = oe_credit.transform(x_test[['credit_rating']])

x_train = x_train_encoded
x_test = x_test_encoded

x_train.head()

    age  income  student  credit_rating
2   1.0     2.0      0.0            0.0
10  0.0     1.0      1.0            1.0
4   2.0     0.0      1.0            0.0
1   0.0     2.0      0.0            1.0
12  1.0     2.0      1.0            0.0

In [16]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

y_train = le.fit_transform(y_train)
y_test = le.transform(y_test)

In [9]:
from sklearn.naive_bayes import CategoricalNB

In [17]:
model = CategoricalNB()
model.fit(x_train, y_train)

CategoricalNB()

In [18]:
y_pred = model.predict(x_test)
y_pred

array([1, 1, 1])

In [19]:
from sklearn.metrics import accuracy_score


acc = accuracy_score(y_test, y_pred)
print(f"Accuracy:{acc:3%}")

Accuracy:66.666667%

In [20]:
data = {'Actual Value':y_test,
      'Predicted Value':y_pred}

pd.DataFrame(data)

   Actual Value  Predicted Value
0             1                1
1             0                1
2             1                1