In [2]:
import pandas as pd
import numpy as np

from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OrdinalEncoder, OneHotEncoder, LabelEncoder
from sklearn.compose import ColumnTransformer

# Load the dataset
df = pd.read_csv('/content/01 covid_toy.csv')

# Display the dataset
print("COVID Dataset:")
display(df)

# Display column names
print("\nColumn Names:")
print(df.columns.tolist())

# Display dataset information
print("\nDataset Information:")
df.info()

COVID Dataset:

    age  gender  fever   cough       city has_covid
0    60    Male  103.0    Mild    Kolkata        No
1    27    Male  100.0    Mild      Delhi       Yes
2    42    Male  101.0    Mild      Delhi        No
3    31  Female   98.0    Mild    Kolkata        No
4    65  Female  101.0    Mild     Mumbai        No
..  ...     ...    ...     ...        ...       ...
95   12  Female  104.0    Mild  Bangalore        No
96   51  Female  101.0  Strong    Kolkata       Yes
97   20  Female  101.0    Mild  Bangalore        No
98    5  Female   98.0  Strong     Mumbai        No
99   10  Female   98.0  Strong    Kolkata       Yes

[100 rows x 6 columns]

Column Names:
['age', 'gender', 'fever', 'cough', 'city', 'has_covid']

Dataset Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   age        100 non-null    int64
 1   gender     100 non-null    object
 2   fever      90 non-null     float64
 3   cough      100 non-null    object
 4   city       100 non-null    object
 5   has_covid  100 non-null    object
dtypes: float64(1), int64(1), object(4)
memory usage: 4.8+ KB

In [3]:
print("Missing values in each column:")
display(df.isnull().sum().to_frame("Missing Values"))

print("\nGender categories:")
print(df["gender"].unique())

print("\nCough categories:")
print(df["cough"].unique())

print("\nCity categories:")
print(df["city"].unique())

print("\nTarget categories:")
print(df["has_covid"].unique())

Missing values in each column:

           Missing Values
age                     0
gender                  0
fever                  10
cough                   0
city                    0
has_covid               0

Gender categories:
['Male' 'Female']

Cough categories:
['Mild' 'Strong']

City categories:
['Kolkata' 'Delhi' 'Mumbai' 'Bangalore']

Target categories:
['No' 'Yes']

In [4]:
# Input features
X = df.drop("has_covid", axis=1)

# Target column
y = df["has_covid"]

print("Input Features (X):")
display(X)

print("\nTarget Column (y):")
display(y.to_frame())

Input Features (X):

    age  gender  fever   cough       city
0    60    Male  103.0    Mild    Kolkata
1    27    Male  100.0    Mild      Delhi
2    42    Male  101.0    Mild      Delhi
3    31  Female   98.0    Mild    Kolkata
4    65  Female  101.0    Mild     Mumbai
..  ...     ...    ...     ...        ...
95   12  Female  104.0    Mild  Bangalore
96   51  Female  101.0  Strong    Kolkata
97   20  Female  101.0    Mild  Bangalore
98    5  Female   98.0  Strong     Mumbai
99   10  Female   98.0  Strong    Kolkata

[100 rows x 5 columns]

Target Column (y):

   has_covid
0         No
1        Yes
2         No
3         No
4         No
..       ...
95        No
96       Yes
97        No
98        No
99       Yes

[100 rows x 1 columns]

In [5]:
transformer = [
    ('trans1', SimpleImputer(), ['fever']),

    ('trans2',
     OrdinalEncoder(categories=[['Mild', 'Strong']]),
     ['cough']),

    ('trans3',
     OneHotEncoder(sparse_output=False, drop='first'),
     ['gender', 'city'])
]

print("Transformers created successfully.")

Transformers created successfully.

In [6]:
ct = ColumnTransformer(
    transformers=transformer,
    remainder='passthrough'
)

X_transformed = ct.fit_transform(X)

print("Transformed Input Data:")
display(pd.DataFrame(
    X_transformed,
    columns=ct.get_feature_names_out()
))

Transformed Input Data:

,trans1__fever,trans2__cough,trans3__gender_Male,trans3__city_Delhi,trans3__city_Kolkata,trans3__city_Mumbai,remainder__age
0,103.0,0.0,1.0,0.0,1.0,0.0,60.0
1,100.0,0.0,1.0,1.0,0.0,0.0,27.0
2,101.0,0.0,1.0,1.0,0.0,0.0,42.0
3,98.0,0.0,0.0,0.0,1.0,0.0,31.0
4,101.0,0.0,0.0,0.0,0.0,1.0,65.0
...,...,...,...,...,...,...,...
95,104.0,0.0,0.0,0.0,0.0,0.0,12.0
96,101.0,1.0,0.0,0.0,1.0,0.0,51.0
97,101.0,0.0,0.0,0.0,0.0,0.0,20.0
98,98.0,1.0,0.0,0.0,0.0,1.0,5.0
99,98.0,1.0,0.0,0.0,1.0,0.0,10.0

In [7]:
le = LabelEncoder()

y_encoded = le.fit_transform(y)

print("Original Target Values:")
print(y.tolist())

print("\nEncoded Target Values:")
print(y_encoded)

print("\nLabel Mapping:")
for label, encoded_value in zip(le.classes_, range(len(le.classes_))):
    print(label, "=", encoded_value)

Original Target Values:
['No', 'Yes', 'No', 'No', 'No', 'Yes', 'No', 'Yes', 'No', 'No', 'No', 'Yes', 'No', 'Yes', 'No', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'No', 'No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes', 'No', 'No', 'No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'No', 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'Yes', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'No', 'Yes']

Encoded Target Values:
[0 1 0 0 0 1 0 1 0 0 0 1 0 1 0 1 1 0 1 1 0 1 1 1 0 0 1 0 0 1 1 0 1 0 1 0 0
 0 1 0 0 1 1 1 0 0 0 0 0 0 1 1 1 1 1 1 0 0 1 1 1 0 1 0 0 0 0 0 0 0 0 0 0 1
 0 1 1 0 1 1 1 0 1 0 0 1 1 0 0 0 0 1 0 1 1 0 1 0 0 1]

Label Mapping:
No = 0
Yes = 1

In [8]:
# Convert transformed features into a DataFrame
X_final = pd.DataFrame(
    X_transformed,
    columns=ct.get_feature_names_out()
)

# Add the encoded target column
X_final["has_covid"] = y_encoded

print("Final Processed COVID Dataset:")
display(X_final)

print("\nFinal Dataset Shape:")
print(X_final.shape)

print("\nCheck Missing Values:")
display(X_final.isnull().sum().to_frame("Missing Values"))

Final Processed COVID Dataset:

,trans1__fever,trans2__cough,trans3__gender_Male,trans3__city_Delhi,trans3__city_Kolkata,trans3__city_Mumbai,remainder__age,has_covid
0,103.0,0.0,1.0,0.0,1.0,0.0,60.0,0
1,100.0,0.0,1.0,1.0,0.0,0.0,27.0,1
2,101.0,0.0,1.0,1.0,0.0,0.0,42.0,0
3,98.0,0.0,0.0,0.0,1.0,0.0,31.0,0
4,101.0,0.0,0.0,0.0,0.0,1.0,65.0,0
...,...,...,...,...,...,...,...,...
95,104.0,0.0,0.0,0.0,0.0,0.0,12.0,0
96,101.0,1.0,0.0,0.0,1.0,0.0,51.0,1
97,101.0,0.0,0.0,0.0,0.0,0.0,20.0,0
98,98.0,1.0,0.0,0.0,0.0,1.0,5.0,0
99,98.0,1.0,0.0,0.0,1.0,0.0,10.0,1

Final Dataset Shape:
(100, 8)

Check Missing Values:

                      Missing Values
trans1__fever                      0
trans2__cough                      0
trans3__gender_Male                0
trans3__city_Delhi                 0
trans3__city_Kolkata               0
trans3__city_Mumbai                0
remainder__age                     0
has_covid                          0